// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixmul_matrixmul,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.417000,HLS_SYN_LAT=32,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=238,HLS_SYN_LUT=406,HLS_VERSION=2022_1}" *)

module matrixmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        res_address0,
        res_ce0,
        res_we0,
        res_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [3:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [3:0] res_address0;
output   res_ce0;
output   res_we0;
output  [15:0] res_d0;

reg ap_idle;
reg a_ce0;
reg b_ce0;
reg res_ce0;
reg res_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln55_fu_160_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln57_fu_254_p2;
reg   [0:0] or_ln57_reg_463;
reg   [0:0] or_ln57_reg_463_pp0_iter1_reg;
reg   [0:0] or_ln57_reg_463_pp0_iter2_reg;
wire   [3:0] add_ln59_fu_280_p2;
reg   [3:0] add_ln59_reg_468;
reg   [3:0] add_ln59_reg_468_pp0_iter1_reg;
reg   [3:0] add_ln59_reg_468_pp0_iter2_reg;
reg   [3:0] add_ln59_reg_468_pp0_iter3_reg;
wire   [0:0] icmp_ln61_1_fu_332_p2;
reg   [0:0] icmp_ln61_1_reg_483;
reg   [0:0] icmp_ln61_1_reg_483_pp0_iter1_reg;
reg   [0:0] icmp_ln61_1_reg_483_pp0_iter2_reg;
reg   [0:0] icmp_ln61_1_reg_483_pp0_iter3_reg;
wire   [63:0] zext_ln62_2_fu_296_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln62_3_fu_321_p1;
wire   [63:0] zext_ln59_1_fu_398_p1;
reg   [15:0] empty_fu_64;
wire   [15:0] grp_fu_406_p3;
reg   [15:0] ap_sig_allocacmp_p_load;
wire    ap_loop_init;
reg   [1:0] k_fu_68;
wire   [1:0] add_ln61_fu_326_p2;
reg   [1:0] ap_sig_allocacmp_k_load;
reg   [1:0] j_fu_72;
wire   [1:0] select_ln57_2_fu_268_p3;
reg   [1:0] ap_sig_allocacmp_j_load;
reg   [3:0] indvar_flatten_fu_76;
wire   [3:0] select_ln57_3_fu_347_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load_1;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [1:0] i_fu_80;
wire   [1:0] select_ln55_1_fu_204_p3;
reg   [1:0] ap_sig_allocacmp_i_load;
reg   [4:0] indvar_flatten15_fu_84;
wire   [4:0] add_ln55_1_fu_166_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten15_load;
wire   [0:0] icmp_ln57_fu_190_p2;
wire   [1:0] add_ln55_fu_184_p2;
wire   [3:0] tmp_fu_216_p3;
wire   [3:0] zext_ln62_fu_212_p1;
wire   [0:0] icmp_ln61_fu_236_p2;
wire   [0:0] xor_ln55_fu_230_p2;
wire   [1:0] select_ln55_fu_196_p3;
wire   [0:0] and_ln55_fu_242_p2;
wire   [1:0] add_ln57_fu_248_p2;
wire   [3:0] sub_ln62_fu_224_p2;
wire   [3:0] zext_ln59_fu_276_p1;
wire   [1:0] select_ln57_fu_260_p3;
wire   [3:0] zext_ln62_1_fu_286_p1;
wire   [3:0] add_ln62_1_fu_290_p2;
wire   [3:0] tmp_1_fu_301_p3;
wire   [3:0] sub_ln62_1_fu_309_p2;
wire   [3:0] add_ln62_2_fu_315_p2;
wire   [3:0] add_ln57_1_fu_341_p2;
wire   [15:0] grp_fu_406_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_140;
reg    ap_condition_141;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixmul_mac_muladd_8s_8s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16ns_16_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_q0),
    .din1(a_q0),
    .din2(grp_fu_406_p2),
    .ce(1'b1),
    .dout(grp_fu_406_p3)
);

matrixmul_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_140)) begin
            empty_fu_64 <= 16'd3;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            empty_fu_64 <= grp_fu_406_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((icmp_ln55_fu_160_p2 == 1'd0)) begin
            i_fu_80 <= select_ln55_1_fu_204_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((icmp_ln55_fu_160_p2 == 1'd0)) begin
            indvar_flatten15_fu_84 <= add_ln55_1_fu_166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten15_fu_84 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((icmp_ln55_fu_160_p2 == 1'd0)) begin
            indvar_flatten_fu_76 <= select_ln57_3_fu_347_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_76 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((icmp_ln55_fu_160_p2 == 1'd0)) begin
            j_fu_72 <= select_ln57_2_fu_268_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_72 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        if ((icmp_ln55_fu_160_p2 == 1'd0)) begin
            k_fu_68 <= add_ln61_fu_326_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_68 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_160_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_reg_468 <= add_ln59_fu_280_p2;
        icmp_ln61_1_reg_483 <= icmp_ln61_1_fu_332_p2;
        or_ln57_reg_463 <= or_ln57_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_reg_468_pp0_iter1_reg <= add_ln59_reg_468;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln61_1_reg_483_pp0_iter1_reg <= icmp_ln61_1_reg_483;
        or_ln57_reg_463_pp0_iter1_reg <= or_ln57_reg_463;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln59_reg_468_pp0_iter2_reg <= add_ln59_reg_468_pp0_iter1_reg;
        add_ln59_reg_468_pp0_iter3_reg <= add_ln59_reg_468_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln61_1_reg_483_pp0_iter2_reg <= icmp_ln61_1_reg_483_pp0_iter1_reg;
        icmp_ln61_1_reg_483_pp0_iter3_reg <= icmp_ln61_1_reg_483_pp0_iter2_reg;
        or_ln57_reg_463_pp0_iter2_reg <= or_ln57_reg_463_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_160_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten15_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten15_load = indvar_flatten15_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load_1 = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_load = 2'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_p_load = grp_fu_406_p3;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        res_ce0 = 1'b1;
    end else begin
        res_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln61_1_reg_483_pp0_iter3_reg == 1'd1))) begin
        res_we0 = 1'b1;
    end else begin
        res_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = zext_ln62_2_fu_296_p1;

assign add_ln55_1_fu_166_p2 = (ap_sig_allocacmp_indvar_flatten15_load + 5'd1);

assign add_ln55_fu_184_p2 = (ap_sig_allocacmp_i_load + 2'd1);

assign add_ln57_1_fu_341_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln57_fu_248_p2 = (select_ln55_fu_196_p3 + 2'd1);

assign add_ln59_fu_280_p2 = (sub_ln62_fu_224_p2 + zext_ln59_fu_276_p1);

assign add_ln61_fu_326_p2 = (select_ln57_fu_260_p3 + 2'd1);

assign add_ln62_1_fu_290_p2 = (sub_ln62_fu_224_p2 + zext_ln62_1_fu_286_p1);

assign add_ln62_2_fu_315_p2 = (sub_ln62_1_fu_309_p2 + zext_ln59_fu_276_p1);

assign and_ln55_fu_242_p2 = (xor_ln55_fu_230_p2 & icmp_ln61_fu_236_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_140 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1));
end

always @ (*) begin
    ap_condition_141 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_address0 = zext_ln62_3_fu_321_p1;

assign grp_fu_406_p2 = ((or_ln57_reg_463_pp0_iter2_reg[0:0] == 1'b1) ? 16'd3 : ap_sig_allocacmp_p_load);

assign icmp_ln55_fu_160_p2 = ((ap_sig_allocacmp_indvar_flatten15_load == 5'd27) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_190_p2 = ((ap_sig_allocacmp_indvar_flatten_load_1 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln61_1_fu_332_p2 = ((add_ln61_fu_326_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_236_p2 = ((ap_sig_allocacmp_k_load == 2'd3) ? 1'b1 : 1'b0);

assign or_ln57_fu_254_p2 = (icmp_ln57_fu_190_p2 | and_ln55_fu_242_p2);

assign res_address0 = zext_ln59_1_fu_398_p1;

assign res_d0 = grp_fu_406_p3;

assign select_ln55_1_fu_204_p3 = ((icmp_ln57_fu_190_p2[0:0] == 1'b1) ? add_ln55_fu_184_p2 : ap_sig_allocacmp_i_load);

assign select_ln55_fu_196_p3 = ((icmp_ln57_fu_190_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_load);

assign select_ln57_2_fu_268_p3 = ((and_ln55_fu_242_p2[0:0] == 1'b1) ? add_ln57_fu_248_p2 : select_ln55_fu_196_p3);

assign select_ln57_3_fu_347_p3 = ((icmp_ln57_fu_190_p2[0:0] == 1'b1) ? 4'd1 : add_ln57_1_fu_341_p2);

assign select_ln57_fu_260_p3 = ((or_ln57_fu_254_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_k_load);

assign sub_ln62_1_fu_309_p2 = (tmp_1_fu_301_p3 - zext_ln62_1_fu_286_p1);

assign sub_ln62_fu_224_p2 = (tmp_fu_216_p3 - zext_ln62_fu_212_p1);

assign tmp_1_fu_301_p3 = {{select_ln57_fu_260_p3}, {2'd0}};

assign tmp_fu_216_p3 = {{select_ln55_1_fu_204_p3}, {2'd0}};

assign xor_ln55_fu_230_p2 = (icmp_ln57_fu_190_p2 ^ 1'd1);

assign zext_ln59_1_fu_398_p1 = add_ln59_reg_468_pp0_iter3_reg;

assign zext_ln59_fu_276_p1 = select_ln57_2_fu_268_p3;

assign zext_ln62_1_fu_286_p1 = select_ln57_fu_260_p3;

assign zext_ln62_2_fu_296_p1 = add_ln62_1_fu_290_p2;

assign zext_ln62_3_fu_321_p1 = add_ln62_2_fu_315_p2;

assign zext_ln62_fu_212_p1 = select_ln55_1_fu_204_p3;

endmodule //matrixmul
